name = "backend"
compatibility_date="2023-12-01"

[vars]
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19IS2ZDSmZnU1V6bUFudUR0TnlkcHkiLCJhcGlfa2V5IjoiMDFLM0JNMkdNSk4xUllSSlczRkM3TjNWUVAiLCJ0ZW5hbnRfaWQiOiJmNDg1NjI5NDA5ZDlmOTBlOGNhYWMzYWE4MTU1N2VkYzllMDlmNjJhNWJhYzZhZTA5ZjYxYmY5MGNiNjI1ZDA0IiwiaW50ZXJuYWxfc2VjcmV0IjoiYjhiNGNlMGUtNWU5Mi00NWM2LWExZGItNGFhNmM2OTVhNDk3In0.JNIghMC9rqtx0QMTRRFmSK_nwVypbeT5o0fswDQ1YJU"
JWT_SECRET="secret"